plugins:
- jekyll-redirect-from
- jekyll-sitemap
- algoliasearch-jekyll

# ---
# Assets
# ---
imgurl: https://images.plot.ly/plotly-documentation/

# ---
# Excludes
# ---
exclude: ['*.Rmd', vendor, node_modules]

# ---
# Markdown / Syntax
# ---
kramdown:
  input: GFM
markdown: redcarpet
redcarpet:
  extensions: ["tables", "fenced_code_blocks"]

# ---
# Algolia Search (R docs)
# ---
# Run: bundle exec jekyll algolia push

algolia:
  application_id: 'X2BCODRMHJ'
  index_name:     'r_docs'
  read_only_api_key: '24b52859fd9a7fb10adcf642f4ae59a5'
  excluded_files:
    - '*.png'
    - '*.Rmd'
    - '*.R'
  settings:
    attributesToIndex:
      - name
      - description
      - title
      - h1
      - h2
      - h3
      - h4
      - h5
      - h6
      - unordered(text)
      - unordered(tags)

excerpt_separator: <!-- excerpt-end -->
